[package]
name    = "translator-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
metal          = ["llama-cpp-2/metal"]
cuda           = ["llama-cpp-2/cuda"]
opentelemetry  = ["dep:opentelemetry"]

[dependencies]
llama-cpp-2          = { workspace = true }
serde_json           = { workspace = true }
lingua               = { workspace = true }
thiserror            = { workspace = true }
serde                = { workspace = true }
tracing              = { workspace = true }
rand                 = { version = "0.8", features = ["small_rng"] }
crossbeam-channel    = "0.5"
rayon                = "1"
encoding_rs          = "0.8"
unicode-segmentation = "1"
opentelemetry        = { workspace = true, optional = true }
