[package]
name    = "translator-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
cuda = ["ct2rs/cuda-dynamic-loading"]

[dependencies]
ct2rs     = { workspace = true }
lingua    = { workspace = true }
tokio     = { workspace = true, features = ["rt"] }
thiserror = { workspace = true }
serde     = { workspace = true }
tracing   = { workspace = true }
