[workspace]
members = ["translator-core", "translator-api", "translator-cli"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
translator-core = { path = "./translator-core" }
tokio            = { version = "1" }
thiserror        = "2"
anyhow           = "1"
serde            = { version = "1", features = ["derive"] }
serde_json       = "1"
tracing          = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ct2rs            = { version = "0.9", features = ["sentencepiece"] }
lingua           = "1"
dashmap          = "6"
clap             = { version = "4", features = ["derive"] }
axum             = { version = "0.8", features = ["json", "macros"] }
tower-http       = { version = "0.6", features = ["trace"] }
