[package]
name    = "translator-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ut"
path = "src/main.rs"

[features]
default = []
metal   = ["translator-core/metal"]
cuda    = ["translator-core/cuda"]

[dependencies]
translator-core    = { workspace = true }
dirs               = { workspace = true }
lingua             = { workspace = true }
clap               = { workspace = true }
tokio              = { workspace = true, features = ["rt-multi-thread", "macros"] }
serde_json         = { workspace = true }
anyhow             = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
